@echo off
setlocal enabledelayedexpansion
chcp 936 >nul

rem ==========================================================================
rem  gen_vhdl_ls_toml.bat
rem  把本文件放到 Vivado 工程根目录, 双击即可生成 vhdl_ls.toml
rem ==========================================================================
rem  扫描手写 VHDL 源 (整个 sources_1 与 sim_1, 含用户自建子目录如 da_module/),
rem  按目录生成 glob 模式 (*.vhd, 非递归, 不含 ip/bd 生成网表/stub 及"副本"备份).
rem  库名 defaultlib (work 是保留字); 路径正斜杠; 若源码用到 unisim 则自动追加
rem  [libraries.unisim] (VPKG+VCOMP, is_third_party=true). Vivado 自动探测
rem  C:\Xilinx\Vivado\* 取最高版本 (本机 2017.4 / 2018.3 -> 取 2018.3).
rem  可选参数 (命令行): /preview 只看不写  /absolute 绝对路径  /vivado PATH 指定版本

set "ABSOLUTE=0"
set "MODE=gen"
set "VIVADO="

:parse
if "%~1"=="" goto run
if /i "%~1"=="/preview"  (set "MODE=preview" & shift & goto parse)
if /i "%~1"=="/absolute" (set "ABSOLUTE=1" & shift & goto parse)
if /i "%~1"=="/vivado"   (set "VIVADO=%~2" & shift & shift & goto parse)
if /i "%~1"=="/help"     goto :help
shift
goto parse

:run
rem 工程根 = 本 .bat 所在目录 (不依赖当前目录, 双击可靠)
set "ROOT=%~dp0"
if "!ROOT:~-1!"=="\" set "ROOT=!ROOT:~0,-1!"
set "PREFIX=!ROOT!\"
set "WINROOT=!ROOT:\=/!"

pushd "!ROOT!" 2>nul
if errorlevel 1 (
  echo [错误] 无法进入工程根: !ROOT!
  pause
  exit /b 1
)

rem --- 扫描手写源: 白名单整个 sources_1/sim_1 + 黑名单 ip/bd 生成物 ---
set "TMPF=%TEMP%\vhdl_ls_files_%RANDOM%%RANDOM%.txt"
dir /s /b *.vhd *.vhdl 2>nul ^
  | findstr /i /l "sources_1\ sim_1\ uisrc" ^
  | findstr /v /i /l ".cache .ip_user_files .runs .gen .hw sources_1\ip sim_1\bd \bd\sim \bd\synth \bd\ip \bd\ipshared \ip\ \sim\ \synth\ \misc\" ^
  | findstr /v /i /l "_sim_netlist _stub _synth .vho _vo _rfs 副本" ^
  | sort > "%TMPF%" 2>nul

set /a FCOUNT=0
for /f "usebackq delims=" %%L in ("%TMPF%") do set /a FCOUNT+=1

rem --- 提取去重目录 (相对路径, 正斜杠, 末尾带/) → 用于生成 glob 模式 ---
rem  TMPF 已按完整路径排序, 同目录文件必相邻, 故相邻去重即可.
set "TMPDIRS=%TEMP%\vhdl_ls_dirs_%RANDOM%%RANDOM%.txt"
set "PREV="
>"%TMPDIRS%" (
  for /f "usebackq delims=" %%L in ("%TMPF%") do (
    set "d=%%~dpL"
    set "rel=!d:%PREFIX%=!"
    set "rel=!rel:\=/!"
    if /i not "!rel!"=="!PREV!" (
      echo !rel!
      set "PREV=!rel!"
    )
  )
)
set /a DCOUNT=0
for /f "usebackq delims=" %%L in ("%TMPDIRS%") do set /a DCOUNT+=1

rem --- unisim 检测 (在源文件里找 library/use unisim) ---
set "NEED_UNISIM=0"
for /f "usebackq delims=" %%L in ("%TMPF%") do (
  if !NEED_UNISIM! equ 0 (
    findstr /i /c:"library unisim" /c:"use unisim" "%%L" >nul 2>&1 && set "NEED_UNISIM=1"
  )
)

rem --- Vivado / unisim 路径探测 ---
set "UNISIM_DIR="
if !NEED_UNISIM! equ 1 (
  if defined VIVADO (
    if exist "!VIVADO!\data\vhdl\src\unisims\unisim_VPKG.vhd" (
      set "UNISIM_DIR=!VIVADO!\data\vhdl\src\unisims"
    ) else (
      echo [警告] --vivado 路径下找不到 unisim: !VIVADO!
    )
  ) else (
    for /d %%D in ("C:\Xilinx\Vivado\*") do (
      if exist "%%D\data\vhdl\src\unisims\unisim_VPKG.vhd" set "UNISIM_DIR=%%D\data\vhdl\src\unisims"
    )
    if not defined UNISIM_DIR echo [警告] 源码用到 unisim 但未找到 Vivado, 用 /vivado 指定.
  )
)
if defined UNISIM_DIR set "UNISIM_DIR=!UNISIM_DIR:\=/!"

if "!MODE!"=="preview" goto preview

rem --- 写 vhdl_ls.toml (注释用英文: toml 是 UTF-8, vhdl_ls 按 UTF-8 读) ---
if exist "vhdl_ls.toml" (
  copy /y "vhdl_ls.toml" "vhdl_ls.toml.bak" >nul
  echo 已备份旧配置: vhdl_ls.toml.bak
)

> "vhdl_ls.toml" (
  echo # vhdl_ls.toml - auto-generated by gen_vhdl_ls_toml.bat
  echo # Project root: !WINROOT!
  echo # !FCOUNT! sources in !DCOUNT! dirs. Glob mode ^(*.vhd, non-recursive^). Generated netlists/stubs excluded.
  echo # Library name: defaultlib ^(work is reserved, cannot be declared in toml^).
  echo.
  echo [libraries]
  echo.
  echo [libraries.defaultlib]
  echo files = [
)

for /f "usebackq delims=" %%L in ("%TMPDIRS%") do (
  set "dir=%%L"
  if "!ABSOLUTE!"=="1" (set "line=!WINROOT!/!dir!*.vhd") else (set "line=!dir!*.vhd")
  echo   "!line!",>>"vhdl_ls.toml"
)
echo ]>>"vhdl_ls.toml"

if !NEED_UNISIM! equ 1 if defined UNISIM_DIR (
  >>"vhdl_ls.toml" (
    echo.
    echo [libraries.unisim]
    echo files = [
    echo   "!UNISIM_DIR!/unisim_VPKG.vhd",
    echo   "!UNISIM_DIR!/unisim_VCOMP.vhd",
    echo ]
    echo is_third_party = true
  )
)

echo.
echo 已生成: vhdl_ls.toml
echo   工程根:       !WINROOT!
echo   手写源文件数: !FCOUNT!  (目录数: !DCOUNT!)
if !NEED_UNISIM! equ 1 (echo   unisim: 是 ^( !UNISIM_DIR! ^)) else (echo   unisim: 否)
if "!ABSOLUTE!"=="1" (echo   路径模式: 绝对) else (echo   路径模式: 相对)
goto cleanup

:preview
echo === 预览模式 (不写文件) ===
echo 工程根: !WINROOT!
echo 手写源文件数: !FCOUNT!  (目录数: !DCOUNT!)
if !NEED_UNISIM! equ 1 (echo 用 unisim: 是 ^( !UNISIM_DIR! ^)) else (echo 用 unisim: 否)
echo ---- toml ----
echo # vhdl_ls.toml - auto-generated by gen_vhdl_ls_toml.bat
echo # Project root: !WINROOT!
echo # !FCOUNT! sources in !DCOUNT! dirs. Glob mode (*.vhd, non-recursive). Generated netlists/stubs excluded.
echo [libraries]
echo.
echo [libraries.defaultlib]
echo files = [
for /f "usebackq delims=" %%L in ("%TMPDIRS%") do (
  set "dir=%%L"
  if "!ABSOLUTE!"=="1" (set "line=!WINROOT!/!dir!*.vhd") else (set "line=!dir!*.vhd")
  echo   "!line!",
)
echo ]
if !NEED_UNISIM! equ 1 if defined UNISIM_DIR (
  echo.
  echo [libraries.unisim]
  echo files = [
  echo   "!UNISIM_DIR!/unisim_VPKG.vhd",
  echo   "!UNISIM_DIR!/unisim_VCOMP.vhd",
  echo ]
  echo is_third_party = true
)
goto cleanup

:help
echo 用法: gen_vhdl_ls_toml.bat [/preview] [/absolute] [/vivado PATH]
echo   把本文件放到 Vivado 工程根目录, 双击生成 vhdl_ls.toml.
echo   输出按目录的 glob 模式 (非递归 *.vhd), 增删源后重启 vhdl_ls 即重新展开.
echo   /preview   只打印不写文件
echo   /absolute  绝对路径 (默认相对工程根)
echo   /vivado P  指定 Vivado 根, 如 C:\Xilinx\Vivado\2018.3
goto cleanup

:cleanup
if exist "%TMPF%" del "%TMPF%" 2>nul
if exist "%TMPDIRS%" del "%TMPDIRS%" 2>nul
popd
echo.
pause
endlocal
